version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: echo 'export MY_ORB_TEMPLATE=$(cat project/slack_template/tests_failed.json)' >> $BASH_ENV
      - slack/notify:
          template: MY_ORB_TEMPLATE
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets