version: '2.1'
 
orbs:
  slack: circleci/slack@4.2.1

jobs:
  job1: 
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
         command: |
          ARTIFACT=$(curl -X GET https://circleci.com/api/v1.1/project/bitbucket/ispottv/qaautomationframework/1199/artifacts -H "circle-token: $CIRCLECI_TOKEN" | jq '.[0].url' )
          echo "export ARTIFACT_URL=$ARTIFACT" >> $BASH_ENV
      - run: echo "$ARTIFACT_URL"
      - slack/notify:
          channel: slacktest
          event: always
          custom: |
           {
2
    "blocks": [
3
        {
4
            "type": "section",
5
            "text": {
6
                "type": "plain_text",
7
                "text": "Your build has passed!",
8
                "emoji": true
9
            }
10
        },
11
        {
12
            "type": "section",
13
            "text": {
14
                "type": "mrkdwn",
15
                "text": "Click the button to download your test results."
16
            },
17
            "accessory": {
18
                "type": "button",
19
                "text": {
20
                    "type": "plain_text",
21
                    "text": "Download Artifacts",
22
                    "emoji": true
23
                },
24
                "value": "artifacts_url",
25
                "url": "$ARTIFACTS_URL",
26
                "action_id": "button-action"
27
            }
28
        }
29
    ]
30
}

workflows:
  send-notification:
    jobs:
      - job1:
          context: slack-secrets
