version: '2.1'
 
orbs:
  slack: circleci/slack@4.2.1

jobs:
  job1: 
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
      - run:
         command: |
          ARTIFACT=$(curl -X GET https://circleci.com/api/v1.1/project/github/ogii-test/slack-orb-template/$CIRCLE_BUILD_NUM/artifacts -H "circle-token: $CIRCLECI_TOKEN" | jq 'try .[0].url catch "https://circleci.com"')
          if [[ -z ${ARTIFACT+x} ]]; then ARTIFACT=https://circleci.com; else echo "Valid Link";fi
          echo "export ARTIFACT_URL=$ARTIFACT" >> $BASH_ENV
      - run: echo "$ARTIFACT_URL"
      - slack/notify:
          channel: slacktest
          event: always
          custom: |
           {
                 "text": "CircleCI job succeeded!",
                 "blocks": [
                    {
                       "type": "header",
                       "text": {
                          "type": "plain_text",
                          "text": "Job Succeeded. :white_check_mark:",
                          "emoji": true
                       }
                    },
                    {
                       "type": "section",
                       "fields": [
                          {
                             "type": "mrkdwn",
                             "text": "*Job*: ${CIRCLE_JOB}"
                          }
                       ]
                    },
                    {
                       "type": "section",
                       "fields": [
                          {
                             "type": "mrkdwn",
                             "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                          },
                          {
                             "type": "mrkdwn",
                             "text": "*Branch*: $CIRCLE_BRANCH"
                                },
                                {
                             "type": "mrkdwn",
                             "text": "*Commit*: $CIRCLE_SHA1"
                          }
                       ],
                       "accessory": {
                          "type": "image",
                          "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                          "alt_text": "CircleCI logo"
                       }
                    },
                          {
                              "type": "actions",
                              "elements": [{
                              "type": "button",
                              "text": {
                                  "type": "plain_text",
                                  "text": "View More",
                                  "emoji": true
                              },
                              "value":  "view_job",
                              "url":  "$ARTIFACT_URL"
                          }
                          ]
                          }

                 ]
                }

workflows:
  send-notification:
    jobs:
      - job1:
          context: slack-secrets
