version: '2.1'

orbs:
  slack: circleci/slack@4.2.0

jobs:
  job1:
    docker:
      - image: 'circleci/node:15.3.0-browsers' 
    steps:
      - run:
          command: |
            exit 1
  job2:
    docker:
      - image: 'circleci/node:15.3.0-browsers'
    steps:
      - run:
          command: |
            exit 0
  notify:
    docker:
      - image: 'circleci/node:15.3.0-browsers'
    steps:
      - checkout
      - run:
          command: >-
            echo 'export MY_ORB_TEMPLATE_PASS=$(cat
            ./slack_template/tests_passed.json)' >> $BASH_ENV
          name: >-
            Store the content of the success.json template into a custom
            environment variable
      - run:
          command: >-
            echo 'export MY_ORB_TEMPLATE_FAIL=$(cat
            ./slack_template/tests_failed.json)' >> $BASH_ENV
          name: >-
            Store the content of the failure.json template into a custom
            environment variable
      - run:
          command: >-
            echo 'export MY_SLACK_CHANNEL=testing' >> $BASH_ENV
      - slack/notify:
          channel: $MY_SLACK_CHANNEL
          event: pass
          template: MY_ORB_TEMPLATE_PASS
      - slack/notify:
          channel: $MY_SLACK_CHANNEL
          event: fail
          template: MY_ORB_TEMPLATE_FAIL

workflows:
  send-notification:
    jobs:
      - job1
      - notify:
          context: slack-secrets
      - job2
