version: 2.1
 
orbs:
  slack: circleci/slack@4.2.1

jobs:
  test: 
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
         command: |
          ARTIFACT=$(curl -X GET https://circleci.com/api/v1.1/project/bitbucket/ispottv/qaautomationframework/1199/artifacts -H "circle-token: $CIRCLECI_TOKEN" | jq '.[0].url' )
          echo "export ARTIFACT_URL=$ARTIFACT" >> $BASH_ENV
      - slack/notify:
          channel: slacktest
          event: always
          custom: |
            {
              "blocks":[
                {
                  "type":"section",
                  "text":{
                    "type":"plain_text",
                    "text":"Your build has passed!",
                    "emoji":true
                  }
                },
                {
                  "type":"section",
                  "text":{
                    "type":"mrkdwn",
                    "text":"Click the button to download your test results."
                  },
                  "accessory":{
                    "type":"button",
                    "text":{
                      "type":"plain_text",
                      "text":"Download Artifacts",
                      "emoji":true
                    },
                    "value":"artifacts_url",
                    "url":"$ARTIFACTS_URL",
                    "action_id":"button-action"
                  }
                }
              ]
            }

workflows:
  send-notification:
    jobs:
      - test:
          context: slack-secrets
